### ISSUE TITLE
Tutorial issues

### ISSUE THREAD

**Issue by en-tropyc** [anagrambuild/bonsol#95]
# Installation
- Problem with installation:
```zsh
~/Documents/powpow/zkprograms (main ✗) # Install Bonsol CLI, Risc0 Toolchain
curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/anagrambuild/bonsol/refs/heads/main/bin/install.sh | sh
    Updating crates.io index
error: could not find ```cargo-binstall``` in registry ```crates-io``` with version ```=1.0.1```
```
- Solution:
```zsh
cargo install cargo-binstall # removed version 1.0.1
cargo binstall cargo-risczero
cargo risczero install
cargo install bonsol-cli --git https://github.com/anagrambuild/bonsol --features mac
```

# Initialization
- Initialize the project:
```zsh
~/Documents/powpow/zkprograms (main ✗) bonsol init collatz
error: unexpected argument 'collatz' found

Usage: bonsol init [OPTIONS] --project-name <PROJECT_NAME>

For more information, try '--help'.
```
- Solution:
```zsh
bonsol init --project-name collatz
```

# Build
- Build the project:
```zsh
~/Documents/powpow/zkprograms (main ✗) bonsol build collatz/src/main.rs 
error: unexpected argument 'collatz/src/main.rs' found

Usage: bonsol build --zk-program-path <ZK_PROGRAM_PATH>

For more information, try '--help'.
```
- Solution:
```zsh
bonsol build --zk-program-path collatz/
```

# Deploy
- Create an S3 bucket:
```zsh
aws s3api create-bucket \
    --bucket bonsol-pow-pow \
    --region ap-southeast-2 \
    --create-bucket-configuration LocationConstraint=ap-southeast-2
```
- Deploy the program:
```zsh
bonsol deploy \
    --deploy-type s3 \
    --bucket {bucket_name} \
    --access-key {access-key} \
    --secret-key {secret-key} \
    --region {region} \
    --url s3://{bucket_name} \
    --manifest-path collatz/manifest.json \
    --storage-account s3://{bucket_name}
```

**Comment by eureka-cpu** [comment]
Hey @christam96 thanks for this. One small thing on the last part, deploying programs, I realize the cli isn't all that intuitive (especially for which options belong to which deployment type), but the `--url` option is actually only for manual deployment. I'll go ahead and open a PR with these changes. Thanks again for pointing them out! 🙂

**Comment by eureka-cpu** [comment]
For the `bonsol build` command, I don't see anywhere in the docs that specify that the path to the zk program is to `main.rs` but to the project folder instead. Is there somewhere you saw that it said to use the path to main?

**Comment by christam96** [comment]
> For the `bonsol build` command, I don't see anywhere in the docs that specify that the path to the zk program is to `main.rs` but to the project folder instead. Is there somewhere you saw that it said to use the path to main?

You're right, it should be the path to the Bonsol program!
